// generated by stringer -type=ColumnType; DO NOT EDIT

package adt

import "fmt"

const (
	_ColumnType_name_0 = "ColumnTypeBool"
	_ColumnType_name_1 = "ColumnTypeDateColumnTypeCharacterColumnTypeMemo"
	_ColumnType_name_2 = "ColumnTypeDoubleColumnTypeIntColumnTypeShortInt"
	_ColumnType_name_3 = "ColumnTypeTimestampColumnTypeTimeColumnTypeAutoIncrement"
	_ColumnType_name_4 = "ColumnTypeCiCharacter"
)

var (
	_ColumnType_index_0 = [...]uint8{0, 14}
	_ColumnType_index_1 = [...]uint8{0, 14, 33, 47}
	_ColumnType_index_2 = [...]uint8{0, 16, 29, 47}
	_ColumnType_index_3 = [...]uint8{0, 19, 33, 56}
	_ColumnType_index_4 = [...]uint8{0, 21}
)

func (i ColumnType) String() string {
	switch {
	case i == 1:
		return _ColumnType_name_0
	case 3 <= i && i <= 5:
		i -= 3
		return _ColumnType_name_1[_ColumnType_index_1[i]:_ColumnType_index_1[i+1]]
	case 10 <= i && i <= 12:
		i -= 10
		return _ColumnType_name_2[_ColumnType_index_2[i]:_ColumnType_index_2[i+1]]
	case 14 <= i && i <= 16:
		i -= 14
		return _ColumnType_name_3[_ColumnType_index_3[i]:_ColumnType_index_3[i+1]]
	case i == 20:
		return _ColumnType_name_4
	default:
		return fmt.Sprintf("ColumnType(%d)", i)
	}
}
